version: "3.1"
services:
  mysql:
    image: mysql:5.6
    container_name: ${PROJECT_NAME}-mysql
    volumes:
      - ./var/docker/database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    network_mode: bridge

  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    links:
      - php-fpm
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}.local
    network_mode: bridge
    expose:
      - 80

  php-fpm:
    build: docker/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /application
    network_mode: bridge
    links:
      - mysql
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    expose:
      - 9000
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    environment:
      - VIRTUAL_HOST=phpmyadmin.${PROJECT_NAME}.local
      - MYSQL_USERNAME=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - PMA_USERNAME=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_HOSTS=${DB_HOST}
    links:
      - mysql
    network_mode: bridge