version: "3.1"
services:
  postgres:
    image: postgres
    container_name: ${PROJECT_NAME}-postgres
    volumes:
      - ./var/docker/database:/data/postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/posrgres
      TZ: Etc/UCT
      PGTZ: Etc/UCT
    network_mode: bridge
    ports:
      - "5432:5432"

  webserver:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /application
    links:
      - php-fpm
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${PROJECT_NAME}.local
    network_mode: bridge
    expose:
      - 80

  php-fpm:
    build: docker/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /application
    network_mode: bridge
    links:
      - postgres
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
    expose:
      - 9000